### PR TITLE
Update to go1.18

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the Dockerfile.envelope to use go1.18.

Part of:
* https://github.com/m-lab/dev-tracker/issues/735

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/access/37)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
*[`Dockerfile.envelope` line 2 at r1](https://reviewable.io/reviews/m-lab/access/37#-NApocIF3Ar8L1QqtInx:-NApocIG5kTAv2-8yCOw:b-443s2n) ([raw file](https://github.com/m-lab/access/blob/a3069a204863a8fd4535dd8c3257cf9f6902f7da/Dockerfile.envelope#L2)):*
> ```
> # Built the command using a golang base image.
> FROM golang:1.18-alpine3.14 AS build
> ```

Please see my comment regarding `alpine` images in https://github.com/m-lab/ndt-server/pull/375#event-7299799504

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/access/37)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/access/37#-:-NApt23CEleu7XjAn3zP:b-833305)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`Dockerfile.envelope` line 2 at r1](https://reviewable.io/reviews/m-lab/access/37#-NApocIF3Ar8L1QqtInx:-NApt1YaEjGOmspVpT3N:b-896fix) ([raw file](https://github.com/m-lab/access/blob/a3069a204863a8fd4535dd8c3257cf9f6902f7da/Dockerfile.envelope#L2)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Please see my comment regarding `alpine` images in https://github.com/m-lab/ndt-server/pull/375#event-7299799504
</blockquote></details>

Done.

**Review by SaiedKazemi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/access/37#-:-NApzgSC0G7vQDFoH9Lo:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Pull request merged**
